version: 2.1
#orbs:
#  node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9
#    executor:
#      name: node/default
#      tag: '10.4'
    steps:
      - checkout
      - run: echo "npm install"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing"
      - run: npm install
      - run: CI=true npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "hello!"
workflows:
  version: 2.1
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
# hi there must have passed