version: 2.1
#orbs:
#  node: circleci/node@1.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
#    executor:
#      name: node/default
#      tag: '10.4'
    steps:
      - checkout
      - run: echo "Bobby first try!"
#      - node/with-cache:
#          steps:
#            - run: npm install
#      - run: npm run test
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Sally first try!"
  workflows:
    version: 2.1
    bobby_sally:
      jobs:
        - bobby
        - sally