version: 2.1
#orbs:
#  node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: circleci/node:11.1
#    executor:
#      name: node/default
#      tag: '10.4'
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
#      - node/with-cache:
#          steps:
#            - run: npm install
#      - run: npm run test
  test:
    docker:
      - image: circleci/node:11.1
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm test
      - run:
        name: "Run Jest and Collect Coverage Reports"
        command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
  hithere:
    docker:
      - image: circleci/node:11.1
    steps:
      - checkout
      - run: echo "Hello!"      
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere